services:
  webapp:
    build:
      context: .
    container_name: webapp
    env_file:
      - ./.env-example
    command: [ "/docker/webapp.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: webapp_db
    env_file:
      - ./.env-example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build:
      context: .
    container_name: celery
    env_file:
      - ./.env-example
    command: [ "/docker/celery.sh", "celery" ]
    depends_on:
      - webapp
      - redis

  beat:
    build:
      context: .
    container_name: celery_beat
    env_file:
      - ./.env-example
    command: [ "/docker/celery.sh", "beat" ]
    depends_on:
      - webapp
      - redis
      - celery


  flower:
    build:
      context: .
    container_name: flower
    env_file:
      - ./.env-example
    command: [ "/docker/celery.sh", "flower" ]
    ports:
      - "5555:5555"
    depends_on:
      - webapp
      - redis
      - celery

  redis:
    image: redis:7.2.5
    container_name: redis


volumes:
  postgres_data: